FROM gcr.io/bazel-public/bazel:latest as builder
WORKDIR /app
COPY . /app
USER root
RUN bazel build //server --features=fully_static_link

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/build/bin/server/server ./server
EXPOSE 8888
ENTRYPOINT ["./server"]
